# Generated by Django 4.0.6 on 2022-07-23 00:48

import app.models.bus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(upload_to=app.models.bus.get_file_path, verbose_name='img'),
        ),
    ]
